name: Agronomist Updates
on:
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Agronomist
        run: |
          AGRONOMIST_VERSION="v0.5.0"
          WHEEL="agronomist-${AGRONOMIST_VERSION#v}-py3-none-any.whl"
          curl -L -o "$WHEEL" "https://github.com/Ops-Talks/agronomist/releases/download/${AGRONOMIST_VERSION}/${WHEEL}"
          pip install "$WHEEL"

      - name: Run Agronomist
        run: agronomist update --root . --output report.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Multiple PRs
        run: |
          if [ ! -f "report.json" ]; then
            echo "No report.json found."
            exit 0
          fi

          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit."
            exit 0
          fi

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Extract unique modules from report.json
          modules=$(jq -r '.updates[].module' report.json 2>/dev/null | sort -u)

          if [ -z "$modules" ]; then
            echo "No modules found in report.json"
            exit 0
          fi

          # Create a temporary commit with all changes
          git add -A
          git commit -m "[agronomist] temporary commit with all module updates"
          all_changes_commit=$(git rev-parse HEAD)

          # Reset to the state before changes
          git reset --hard HEAD~1

          for module in $modules; do
            echo "Processing module: $module"
            
            # Create branch name from module
            branch_name="agronomist/update-$(echo "$module" | sed 's/\//-/g')"
            
            # Get files affected by this module
            files=$(jq -r --arg mod "$module" '.updates[] | select(.module==$mod) | .files[]' report.json 2>/dev/null)
            
            if [ -z "$files" ]; then
              echo "No files found for module: $module"
              continue
            fi
            
            # Create and checkout new branch from clean state
            git checkout -b "$branch_name"
            
            # Cherry-pick only the files for this module from the temp commit
            echo "$files" | while IFS= read -r file; do
              if [ -n "$file" ]; then
                git checkout "$all_changes_commit" -- "$file" 2>/dev/null || true
              fi
            done
            
            # Check if there are changes
            if [ -z "$(git diff --cached --name-only)" ] && [ -z "$(git diff --name-only)" ]; then
              echo "No changes for module: $module"
              git checkout HEAD~0
              git branch -D "$branch_name" 2>/dev/null || true
              continue
            fi
            
            # Stage and commit changes
            git add -A
            git commit -m "[Agronomist] There is a new Module Version"
            
            # Push branch
            git push -f origin "$branch_name"
            
            # Create PR using GitHub CLI
            gh pr create \
              --title "[Agronomist] Update ${module}" \
              --body "Updates generated by Agronomist." \
              --head "$branch_name" || true
            
            # Return to clean state for next iteration
            git reset --hard HEAD~1
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
