#!/usr/bin/env bash
set -euo pipefail

# Create one Bitbucket Cloud pull request per updated module in report.json.
# Agronomist has already applied all updates to the working tree; this script
# records those changes in a temporary local commit, resets to the base branch,
# then checks out only the files for each module into a dedicated branch.

REPORT_FILE="${REPORT_FILE:-report.json}"
BITBUCKET_BASE_URL="${BITBUCKET_BASE_URL:-https://api.bitbucket.org/2.0}"
PR_BODY="${PR_BODY:-Updates generated by Agronomist.}"
PR_TARGET_BRANCH="${PR_TARGET_BRANCH:-${BITBUCKET_BRANCH:-main}}"
WORKSPACE="${BITBUCKET_WORKSPACE:-}"
REPO_SLUG="${BITBUCKET_REPO_SLUG:-}"
TOKEN="${BITBUCKET_TOKEN:-}"
BASE_BRANCH="$PR_TARGET_BRANCH"

if [ -z "$TOKEN" ]; then
  echo "BITBUCKET_TOKEN not set. Skipping PR creation."
  exit 0
fi

if [ -z "$WORKSPACE" ] || [ -z "$REPO_SLUG" ]; then
  echo "BITBUCKET_WORKSPACE and BITBUCKET_REPO_SLUG are required."
  exit 1
fi

if ! command -v jq >/dev/null 2>&1; then
  echo "jq is required. Install it in the pipeline before running this script."
  exit 1
fi

if [ ! -f "$REPORT_FILE" ]; then
  echo "No $REPORT_FILE found."
  exit 0
fi

if [ -z "$(git status --porcelain)" ]; then
  echo "No changes to commit."
  exit 0
fi

modules=$(jq -r '.updates[]?.module' "$REPORT_FILE" 2>/dev/null | sort -u)
if [ -z "$modules" ]; then
  echo "No modules found in $REPORT_FILE."
  exit 0
fi

# Keep report metadata inside .agronomist-ci so it is not accidentally staged
# as a module update and no external temporary directory is needed.
STATE_DIR=".agronomist-ci"
mkdir -p "$STATE_DIR"
REPORT_COPY="$STATE_DIR/report.json"
cp "$REPORT_FILE" "$REPORT_COPY"

# Capture all Agronomist changes once, excluding report and CI metadata. Each
# per-module branch checks out only its affected files from this commit.
git add -A -- . ":!$REPORT_FILE" ":!$STATE_DIR"
git commit -m "[agronomist] temporary commit with all module updates"
all_changes_commit=$(git rev-parse HEAD)
git reset --hard HEAD~1

if git rev-parse --verify "origin/${BASE_BRANCH}" >/dev/null 2>&1; then
  git checkout -B "$BASE_BRANCH" "origin/${BASE_BRANCH}"
else
  git checkout -B "$BASE_BRANCH"
fi
cp "$REPORT_COPY" "$REPORT_FILE"

cleanup() {
  git checkout "$BASE_BRANCH" >/dev/null 2>&1 || true
  git reset --hard "origin/${BASE_BRANCH}" >/dev/null 2>&1 || git reset --hard >/dev/null 2>&1 || true
  rm -rf "$STATE_DIR"
}
trap cleanup EXIT

api_url="${BITBUCKET_BASE_URL%/}/repositories/${WORKSPACE}/${REPO_SLUG}/pullrequests"

while IFS= read -r module_id; do
  [ -n "$module_id" ] || continue
  echo "Processing module: $module_id"

  base_module="${module_id%%@*}"
  safe_base=$(printf '%s' "$base_module" | sed 's#[/@]#-#g' | cut -c1-50)
  HASH=$(printf '%s' "$module_id" | sha256sum | cut -c1-8)
  branch="agronomist/update-${safe_base}-${HASH}"

  IFS=$'\t' read -r base_module_label latest_ref < <(
    jq -r --arg mod "$module_id" \
      '.updates[] | select(.module==$mod) | [(.base_module // (.module | split("@")[0])), (.latest_ref // "latest")] | @tsv' \
      "$REPORT_COPY" | head -1
  )
  base_module_label="${base_module_label:-$base_module}"
  latest_ref="${latest_ref:-latest}"
  title="[Agronomist] Update ${base_module_label} to ${latest_ref}"

  files=$(jq -r --arg mod "$module_id" '.updates[] | select(.module==$mod) | .files[]?' "$REPORT_COPY")
  if [ -z "$files" ]; then
    echo "No files found for module: $module_id"
    continue
  fi

  git checkout "$BASE_BRANCH"
  git branch -D "$branch" 2>/dev/null || true
  git checkout -b "$branch"

  while IFS= read -r file; do
    [ -n "$file" ] || continue
    git checkout "$all_changes_commit" -- "$file"
  done <<< "$files"

  if [ -z "$(git status --porcelain)" ]; then
    echo "No changes for module: $module_id"
    git checkout "$BASE_BRANCH"
    git branch -D "$branch" 2>/dev/null || true
    continue
  fi

  while IFS= read -r file; do
    [ -n "$file" ] || continue
    git add -- "$file"
  done <<< "$files"
  git commit -m "$title"
  git push origin --delete "$branch" 2>/dev/null || true
  git push -u origin "$branch"

  payload=$(jq -n \
    --arg title "$title" \
    --arg branch "$branch" \
    --arg target "$PR_TARGET_BRANCH" \
    --arg body "$PR_BODY" \
    '{title: $title, source: {branch: {name: $branch}}, destination: {branch: {name: $target}}, description: $body}')

  curl --silent --show-error --fail \
    -X POST \
    -u "x-token-auth:${TOKEN}" \
    -H "Content-Type: application/json" \
    -d "$payload" \
    "$api_url" || echo "Failed to create PR for ${branch}; it may already exist."

done <<< "$modules"
